version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: care_near_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: care_near_db
      POSTGRES_USER: elhas
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - care_near_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: care_near_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  care_near_pgdata:
